__author__ = 'Maple'
from django.conf.urls import patterns, url
from task import views

urlpatterns = patterns('',
                       url(r'^show_task/$', views.show_task),
                       url(r'^all_task/$', views.all_task),
                       url(r'^(?P<my_id>\d+)/show_detail/$', views.show_detail, name="task"),
                       url(r'^task_detail/(.+)/$', views.show_detail),
                       url(r'^add_task/$', views.add_task),
                       url(r'^created_task/$', views.created_task),
                       url(r'^doing_task/$', views.doing_task),
                       url(r'^executed_task/$', views.executed_task),
                       url(r'^comments/p1(\w+)p2(.+)/$', views.comments),
                       url(r'^delete/(.+)/$', views.delete),
                       url(r'^deleteTree/(.+)/$', views.deleteTree),
                       url(r'^checked/(.+)/$', views.checked),
                       url(r'^affirm/(.+)/$', views.affirm),
                       url(r'^submit/(.+)/$', views.submit),
                       #url(r'^modify/p1(\w+)p2(.+)/$', views.modify),
                       url(r'^modify/(.+)/$', views.modify),
                       url(r'^psb_vsb/(.+)/$', views.psb_vsb),
                       url(r'^add_comment/p1(\w+)p2(.+)p3(.+)/$', views.add_comment),
                       url(r'^psb_vsb_add/p1(\w+)p2(.+)/$', views.psb_vsb_add),
                       url(r'^schedule/p1(\w+)p2(.+)/$', views.add_schedule),
                       url(r'^create_taskTemp/(.+)/$', views.create_tsktemp),
                       url(r'^taskTemplate/$', views.taskTemplate),
                       url(r'^addByTemp/(.+)/$', views.addByTemp),
                       url(r'^selectTemp/$', views.selectTemp),
                       url(r'^selTemp_addTsk/(.+)/$', views.selTemp_addTsk),
                       url(r'^delTemp/(.+)/$', views.delTemp),
                       url(r'^get_comments/(?P<task_id>\d+)/$', views.get_comments),
                       url(r'^get_feedbacks/(?P<task_id>\d+)/$', views.get_feedbacks),
)